navigation:
- text: Home
  url: index.html
  permalink: index.html
- text: Installation
  url: installation.html
  permalink: installation.html
#- text: Features
#  url: features
#  permalink: /features
- text: FAQ
  url: faq.html
  permalink: faq.html
